name: build
on:
    push:
        branches: [main]
jobs:
  unit-test:
    permissions: read-all|write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
      - run: make test
      - uses: cicirello/jacoco-badge-generator@v2
        with:
            generate-coverage-badge: true
            generate-branches-badge: true
      - uses: EndBug/add-and-commit@v7
        with:
            default_author: github_actions
            message: 'Updated coverage badges'
            add: '*.svg'
