name: PR Action
on:
    pull_request:
        branches: [main]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
      - uses: cicirello/jacoco-badge-generator@v2 
        with:
            fail-if-coverage-less-than: 50
            generate-coverage-badge: true
            generate-branches-badge: true
      - uses: EndBug/add-and-commit@v7
        with:
            default_author: github_actions
            message: 'Updated coverage badges'
            add: '*.svg'
