name: Tests
on:
    pull_request:
        branches: [main]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make test
      - uses: cicirello/jacoco-badge-generator@v2
        with:
            fail-if-coverage-less-than: 50
