name: Tests
on:
    push:
        branches: [main]
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
            distribution: adopt
            java-version: '17'
      - run: |
          set -x
          java -version
          make test
      - uses: cicirello/jacoco-badge-generator@v2
        with:
            fail-if-coverage-less-than: 50
            generate-coverage-badge: true
            generate-branches-badge: true
      - uses: EndBug/add-and-commit@v8
        with:
            default_author: github_actions
            message: 'Updated coverage badges'
            add: '*.svg'
